import Head from 'next/head'
import "antd/dist/antd.css";
import Banner from '../components/Banner';
import MainHeader from '../components/MainHeader';
import Footer from '../components/Footer';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader />
      <Banner />
      <Footer />
      
    </>
  )
}
