import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.scss'
import { Button, DatePicker, Space, version } from "antd";
import "antd/dist/antd.css";
import Link from 'next/link';
import Banner from '../components/Banner';
import MainHeader from '../components/MainHeader';

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MainHeader />
      <Banner />
       
      <footer className={styles.footer}>
        <small>
          Lucas Gaspar Firmino
        </small>
      </footer>
    </>
  )
}
